name: hpack
version: 0.5.2
synopsis: An alternative format for Haskell packages
maintainer: Simon Hengel <sol@typeful.net>
license: MIT
github: sol/hpack

ghc-options: -Wall

dependencies:
  - aeson >= 0.8
  - base >= 4.7 && < 5
  - base-compat >= 0.8
  - deepseq
  - directory
  - filepath
  - Glob
  - text
  - unordered-containers
  - yaml

library:
  source-dirs: src
  exposed-modules:
    - Hpack.Config
    - Hpack.Run

executables:
  hpack:
    main: Main.hs
    source-dirs: driver
    dependencies: hpack

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - mockery >= 0.3
      - interpolate
      - aeson-qq
